# Generated by Django 3.2.5 on 2021-11-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20211125_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='Tags', to='Blog.Tag'),
        ),
    ]
